## Mustafa Habibi

### Exercise 1
Create a function that, given a one-dimensional Array, gives you a basic statistical summary of the data. If it detects that the array has more than one dimension, it must display an error message.

In [1]:
import numpy as np

def s_array(my_array):
    if my_array.ndim>1:
     print ('Error, this array is one dimension')
    else:
        print("Max value: ", np.max(my_array))
        print("Min value: ", np.min(my_array))
        print("Sum of values: ", np.sum(my_array))
        print("Standard deviation: ", np.std(my_array))
        print("Variance: ", np.var(my_array))
        print("Number of dimensions: ", my_array.ndim)
        
my_array= np.arange(2, 50, 4)

s_array(my_array)


    

Max value:  46
Min value:  2
Sum of values:  288
Standard deviation:  13.808210118138652
Variance:  190.66666666666666
Number of dimensions:  1


In [2]:
my_array = np.array([[2,4,5], [6,5,4]])
s_array(my_array)

Error, this array is one dimension


## Exercise 2
Create a function that generates an NxN square of random numbers between 0 and 100.

In [68]:
import numpy as np

def generate_random_array(shape, low=0, high=100):
    return np.random.randint(low=low, high=high, size=shape)

x = generate_random_array(shape=(9,9))

print(x)

[[78 66 53 77 44 82 35 60  2]
 [87 26 80 21 84 67 21 67 94]
 [93 41 56 20 94 25 91 43  8]
 [ 4 39 85 71 55 28 91 41 54]
 [62 51 23 13 91  3 32 85 47]
 [ 4 90 49 57 60 77 79 83 80]
 [61 72 10 42 21 14 93 71 15]
 [88 65  1 14 79 91 69 59 87]
 [42 14 65 17 24 35 54 40 19]]


In [69]:
def generate_random_array(rows, cols):
    return np.random.randint(0, 100, size=(rows, cols))

# Example usage:
my_array = generate_random_array(9, 9)
print(my_array)

[[18 84 39  3 50 75 21 31 52]
 [85 96 19 77 97 16 77 58 73]
 [68 88 17 37  7 25 31 95 78]
 [57 30 10 37 74 53 22 67 85]
 [54 43 70 18 29 24 38 43 90]
 [53 15 75 22 53 78 13 19 65]
 [ 6 28  1 66 15 68 73 70 68]
 [47 60 89 60 16  8 97  6 60]
 [55 52 44 71 54 29 90 92 47]]


## Exercise 3
Create a function that, given a two-dimensional table (NxM), calculates the totals per row and the totals per column.

In [70]:
def total_p_column(x):
    return x
x = np.array([[2,34,5,6,3,2], [4,5,8,7,8,7], [3,4,7,6,5,4]])
print ('The two dimensional table:',x)
print ('Number of dimensions=',x.ndim)
print ('Totals per row is:',np.sum([x],axis=2))
print ('Totals per columns is:',np.sum([x],axis=1))

The two dimensional table: [[ 2 34  5  6  3  2]
 [ 4  5  8  7  8  7]
 [ 3  4  7  6  5  4]]
Number of dimensions= 2
Totals per row is: [[52 39 29]]
Totals per columns is: [[ 9 43 20 19 16 13]]


## Exercise 4
Manually implement a function that calculates the correlation coefficient. Learn about its uses and interpretation.

In [71]:
# Define two arrays of data:
x= np.array([2, 3, 4, 5, 6, 7, 9])
y= np.array([30, 40, 60, 70, 80, 90, 100])
# calculate the corration coeffecient between 'exame score(y) with study hours (x)'
r= np.corrcoef(x,y)[0,1]

print ('correlation coeffecient calculation result between x and y is: ', r)
# this number shows that the more hours you spend on study, the better score you can get.


calculate the correlation coeffecient between x and y is:  0.9787781425897796
